import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import api from "../services/api";
import { motion } from "framer-motion";
import "./StudentDashboard.css";

/* =========================
   ACTION CARD COMPONENT
   ========================= */
function ActionCard({ icon, title, description, onClick }) {
  return (
    <div className="dashboard-card" onClick={onClick}>
      <div className="card-icon">{icon}</div>
      <h3 className="card-title">{title}</h3>
      <p className="card-description">{description}</p>
    </div>
  );
}

/* =========================
   STUDENT DASHBOARD
   ========================= */
function StudentDashboard() {
  const navigate = useNavigate();

  const [metrics, setMetrics] = useState({
    hallTicketStatus: "unavailable",
    hallTicketValue: "Not Available",
    seatingStatus: "unavailable",
    seatingValue: "Not Allocated",
    upcomingExam: "None",
    approvedEvents: 0,
  });

  const [loading, setLoading] = useState(true);

  /* =========================
     FETCH DASHBOARD METRICS
     ========================= */
  useEffect(() => {
    const fetchMetrics = async () => {
      try {
        const token = localStorage.getItem("token");

        /* Hall Ticket Status */
        try {
          const hallTicketRes = await api.get("/api/hall-tickets/me", {
            headers: { Authorization: `Bearer ${token}` },
          });

          if (hallTicketRes.data?.hallTicket) {
            setMetrics((prev) => ({
              ...prev,
              hallTicketStatus: "available",
              hallTicketValue: "Available",
            }));
          } else {
            setMetrics((prev) => ({
              ...prev,
              hallTicketStatus: "pending",
              hallTicketValue: "Pending",
            }));
          }
        } catch {
          // keep default state
        }

        /* Approved Club Events */
        try {
          const eventsRes = await api.get("/api/club-events/approved", {
            headers: { Authorization: `Bearer ${token}` },
          });

          setMetrics((prev) => ({
            ...prev,
            approvedEvents: eventsRes.data?.events?.length || 0,
          }));
        } catch {
          // graceful fallback
        }
      } finally {
        setLoading(false);
      }
    };

    fetchMetrics();
  }, []);

  /* =========================
     DASHBOARD ACTIONS
     ========================= */
  const actions = [
    {
      icon: "🎫",
      title: "Hall Ticket",
      description: "View and download your hall ticket for exams",
      route: "/student/hall-ticket",
    },
    {
      icon: "🪑",
      title: "Seating Arrangement",
      description: "Check your assigned seat for upcoming exams",
      route: "/student/seat",
    },
    {
      icon: "📅",
      title: "Academic Calendar",
      description: "View important dates and academic schedules",
      route: "/student/calendar",
    },
    {
      icon: "🎉",
      title: "Club Events",
      description: "Explore approved club events and activities",
      route: "/student/club-events",
    },
  ];

  /* =========================
     LOGOUT HANDLER
     ========================= */
  const handleLogout = () => {
    localStorage.removeItem("token");
    navigate("/login");
  };

  /* =========================
     RENDER
     ========================= */
  return (
    <div className="dashboard-container">
      {/* Header (Logout only — branding handled globally) */}
      <header className="dashboard-header">
        <button className="logout-button" onClick={handleLogout}>
          Logout
        </button>
      </header>

      {/* Main Content */}
      <div className="dashboard-content">
        <h1>Student Dashboard</h1>
        <p className="dashboard-subtitle">Quick Actions</p>

        {/* Action Cards */}
        <div className="dashboard-grid">
          {actions.map((action) => (
            <ActionCard
              key={action.title}
              icon={action.icon}
              title={action.title}
              description={action.description}
              onClick={() => navigate(action.route)}
            />
          ))}
        </div>

        {/* Informational Message */}
        {!loading && metrics.hallTicketStatus === "unavailable" && (
          <motion.div
            className="dashboard-message"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
          >
            <div className="message-icon">📋</div>
            <h3>No Hall Ticket Yet</h3>
            <p>
              Your hall ticket will appear here once it has been generated by
              the administrator.
            </p>
            <button
              className="dashboard-button"
              onClick={() => navigate("/student/hall-ticket")}
            >
              Check Hall Ticket Page
            </button>
          </motion.div>
        )}
      </div>
    </div>
  );
}

export default StudentDashboard;
